### PR TITLE
suggest for adding "enableAutoIndent" option to "TextPrettyPrintingConfig"

### PR DESCRIPTION
**Pull request by gkm2164**
related to #22 issue.

- I added enableAutoIndent in TextPrettyPrintingConfig class.
- And at ```addIntentation``` method in ```RenderContext``` class, I added a branch that ignore adding intentation behavior if ```enableAutoIndent``` option in prettyPrinting is ```false```.

### CODE REVIEW

**Comment by gkm2164** [comment]
I modified .travis.yml file, since it shows some HeaderPlugin's known issue.

https://github.com/sbt/sbt-header/issues/153

Previously, you added a line ```disablePlugins("HeaderPlugin")``` on last line of ```build.sbt```
By the way, I found that other library seems to be not enabled.
So I just added ```enablePlugins(HeaderPlugin)``` to each projects without root as you intended.

**Comment by fomkin** [comment]
👍

**Comment by gkm2164** [comment]
> 👍

By the way, when will you release this feature?

**Comment by fomkin** [comment]
https://github.com/fomkin/levsha/releases/tag/v0.7.2
https://github.com/fomkin/korolev/releases/tag/v0.11.1

**Pull request merged**
